### ISSUE TITLE
Vertausarvionti

### ISSUE THREAD

**Issue by CoolMcRad** [HyTom/Luolapeli#1]
218.2020 klo 23.43
## Hyvältä näyttää

Ehkä kannattaa alkaa lisätä eri muuttujia, että saa kiinnostavempia luolastoja generoitua. Myös muuntujia, jotka estää jotkin
tylsemmät generoinnit, kuten pitkät tiet jotka ei johda mihinkään. 

Ehkä muuntujia eri huoneille jotka antaa niille eri muotoja ja biomeja, jotka antavat kaikille alueen huoneille jotain piirteitä.

**Comment by HyTom** [comment]
Huonegeneraattorissa on tällä hetkellä vain 10 reseptiä erilaisille huoneille, mutta voin lisätä niitä helposti lisää.
Kiitos palautteesta!
